services:
  - type: web
    name: voicebot-service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python voicebot.py"
    plan: free
    envVars:
      - key: ASSEMBLY_API_KEY
        value: 1cfced456ed0499c8d67290d2a1272e1
      - key: OPENROUTER_API_KEY
        value: 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
      - key: SENDER_EMAIL
        value: serdar1392@gmail.com
      - key: SENDER_PASSWORD
        value: uvxr mzqo jbue nmdi

